name: Check and Create Release

# Creates mirror release if origin have it
# Run workflow on schedule, and allow manual runs.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # Runs daily at 1:00 AM UTC

permissions:
  contents: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.fetch_latest_tag.outputs.tag }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Get latest release tag from pyocd/libusb-package
        id: fetch_latest_tag
        run: |
          # Fetch the latest release tag from pyocd/libusb-package repository
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/pyocd/libusb-package/releases/latest" | jq -r .tag_name)
          echo "LATEST_TAG=$LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.fetch_latest_tag.outputs.tag }} # Tag for the release
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token
          generate_release_notes: true # Automatically generate release notes if none provided

  build-deploy:
    needs: check-release
    uses: ./.github/workflows/build-deploy.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      tag: ${{ needs.check-release.outputs.tag }}

  build-deploy-test:
    needs: check-release
    uses: ./.github/workflows/build-deploy-test.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      tag: ${{ needs.check-release.outputs.tag }}
