name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Disable default token

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Sync upstream changes
        run: |
          git remote add upstream https://github.com/o-murphy/libusb-package.git
          git fetch upstream
          git checkout main  # Change if using another default branch
          git merge upstream/main --no-edit
          git push https://$PAT@github.com/o-murphy/libusb-package.git main
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
